CREATE TABLE IF NOT EXISTS agent_cards (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  url TEXT NOT NULL,
  agent_card_url TEXT,
  provider_org TEXT,
  provider_url TEXT,
  skills JSONB DEFAULT '[]',
  tags TEXT[] DEFAULT '{}',
  platform TEXT,
  version TEXT,
  protocol_version TEXT DEFAULT '0.3.0',
  capabilities JSONB DEFAULT '{}',
  input_modes TEXT[] DEFAULT '{text}',
  output_modes TEXT[] DEFAULT '{text}',
  contact TEXT,
  likes TEXT[],
  avatar_url TEXT,
  type TEXT DEFAULT 'agent', -- 'agent' or 'service'
  message_count INTEGER DEFAULT 0,
  rating NUMERIC(3,2),
  featured BOOLEAN DEFAULT false,
  verified BOOLEAN DEFAULT false,
  last_seen_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
